### ISSUE TITLE
USER STORY - View a list of products

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#11]
As a **User** I can **View a list of all available products to buy**

## Acceptance Criteria
- Create a page where users can view and select products to buy

## Tasks
- [x]  Create  all products view
- [x]  Create all products url
- [x] Create all products template
