### ISSUE TITLE
USER STORY - View Individual Products

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#12]
As a **User ** I can **View individual products in more detail**

## Acceptance Criteria
- View a product page to see its details

## Tasks

- [x]  Create a product_detail view
- [x] Create a product_detail url
- [x] Create a product_detail template
