### ISSUE TITLE
USER STORY - Home Page

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#13]
As a **User** I can **Arrive at the home page of the site and know the purpose of the site in a clear and welcoming manner**

## Acceptance Criteria
- As a user arrive at the home page and navigate easily and clearly around the site 

## Tasks

- [x] Create home view
- [x] Create home url
- [x] Create home template
