### ISSUE TITLE
USER STORY - Register a new account

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#14]
As a **User** I can **Register a new account so that I can view, update and edit my details and view plans and purchases**

## Acceptance Criteria
- User can register a new account 

## Tasks

- [x]  Ensure all auth is properly installed 
- [x] Create registration option for users
- [x] Allow logged in users to save their personal details
