### ISSUE TITLE
USER STORY - Login and logout of an account

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#16]
As a **User** I can **Login and Logout of my account**

## Acceptance Criteria
- As a user I can navigate to a login and logout page and successfully login or logout

## Tasks

- [x] Edit templates for login and logout pages
- [x] Add links to these pages in navbar
- [x] Ensure users can login and logout succesfully
