### ISSUE TITLE
USER STORY - Post completed session

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#20]
As a **User** I can **Post a completed session using the equipment that I have previously purchased**

## Acceptance Criteria
- User can create a post on a blog style feed where users can post about their exercise sessions

## Tasks

- [x]  Create form to post the users session
- [x]  Create view, template and url to post the session
- [x]  Create view template and url to view all users posts
