### ISSUE TITLE
USER STORY - Edit basket

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#25]
As a **User** I can **Edit the items and quantities in my basket**

## Acceptance Criteria
- User can update and delete items in their basket from the basket template

## Tasks 

- [x] Create checkout template, view and url
- [x]  Create options to update quantities of item in the shopping bag
- [x] Create a delete item option to delete item from the bag
