### ISSUE TITLE
USER STORY - Checkout

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#26]
As a **User** I can **Use stripe to easily checkout and make payment**

## Acceptance Criteria
- Users can use stripe to make payment and checkout 

## Tasks

- [x] Create view template and url for checkout functionality
- [x] Create stripe form
- [x] Ensure form is rendering
- [x] Ensure stripe is functioning as required
