### ISSUE TITLE
USER STORY - Manage Products

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#27]
As a **Business Owner** I can **manage the products on the site**

## Acceptance Criteria
- Ensure that the business owner has a front end option to add, edit and delete products

## Tasks

- [x]  Create add product functionality
- [x] Create edit product functionality
- [x] Create delete product functionality
