### ISSUE TITLE
USER STORY - Manage Coaches

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#28]
As a **Business Owner** I can **add, edit and delete coaches**

## Acceptance Criteria
- Business owners are able to add, edit and delete coaches from the site

## Tasks

- [x] Create Add a coach functionality
- [x] Create edit a coach functionality
- [x] Create delete a coach functionality
