### ISSUE TITLE
USER STORY - Manage Sessions

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/PP5#29]
As a **Business Owner** I can **add, edit and delete Sessions**

## Acceptance Criteria
- Business owner should be able to add,  edit and delete Sessions

## Tasks

- [x] Create add a session functionality
- [x]  Create edit a session functionality
- [x] Create delete a session functionality
